import React from 'react';
import { renderToString } from 'react-dom/server';
import { MessageRenderer } from '../index';
import type { TJoinedMessage, TFile } from '@sharkord/shared';

// stub the `useOwnUserId` hook by patching the imported module. the
// renderer memoizes, so we set the return value before rendering.
import * as userHooks from '@/features/server/users/hooks';
userHooks.useOwnUserId = () => 1;

// most of the renderer output is HTML generated by html-react-parser;
// rendering to string and searching for the expected <img> tags is enough
// to verify the behaviour.

describe('MessageRenderer', () => {
  it('shows uploaded image files inline', () => {
    const file: TFile = {
      id: 123,
      name: 'foo.png',
      originalName: 'foo.png',
      extension: 'png',
      size: 1024,
      userId: 1,
      createdAt: Date.now(),
      _accessToken: undefined
    };

    const msg: TJoinedMessage = {
      id: 1,
      channelId: 1,
      userId: 1,
      content: '',
      editable: true,
      parentMessageId: null,
      createdAt: Date.now(),
      reactions: [],
      files: [file],
      metadata: null
    };

    const output = renderToString(<MessageRenderer message={msg} />);

    // The <img> coming from ImageOverride should appear, referring to the file
    expect(output).toMatch(/src=".*foo.png"/);
    // and the file card link should still exist somewhere
    expect(output).toContain('href="');
  });
});
